### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkarlovi** [dkarlovi/luster#1]
- [ ] ingest log to a SQLite database everything else operates on
- [ ] custom log parser, custom portions (reuse grok patterns?)
- [ ] whitelist / blacklist log items (real or virtual properties), resolve/warn about whitelisted AND blacklisted (AllowDeny, DenyAllow?)
- [ ] sessions detection, session ID, access token, custom
- [ ] session TTL (how much time to interpret as new session)
- [ ] sessions count, start, end, duration, requests
- [ ] requests count, duration, status codes (per session or global)
